name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths:
      - '**/*.tpl'
      - '**/*.py'
      - '**/*.tf'
      - '.github/workflows/release.yml'

env:
  RELEASE_VERSION: "25.0.0"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    # Skip running release workflow on forks
    if: github.repository_owner == 'terraform-aws-modules'
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set correct Node.js version
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        run: |
          npm install \
            @semantic-release/changelog@6.0.3 \
            @semantic-release/git@10.0.1 \
            conventional-changelog-conventionalcommits@9.1.0

      - name: Release
        uses: cycjimmy/semantic-release-action@v5
        with:
          semantic_version: ${{ env.RELEASE_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}

  tofu-modules:
    name: Release OCI artifact
    runs-on: ubuntu-latest
    permissions:
      packages: write # needed to publish oci artifact to ghcr.io
    # Skip running release workflow on forks
    if: github.repository_owner == 'terraform-aws-modules'
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          fetch-depth: 0

      # Login to registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install oras tool
        uses: oras-project/setup-oras@v2.0.0

      - name: Create zip file
        run: |-
          mkdir -p /home/runner/work/modules
          zip -r /home/runner/work/modules/terraform-aws-eks.zip . -x "*.git*"

      - name: Publish Artifact
        working-directory: /home/runner/work/modules
        run: |-
          oras push ghcr.io/${{ github.repository_owner }}/opentofu-modules/eks:latest \
            --artifact-type application/vnd.opentofu.modulepkg \
            terraform-aws-eks.zip:archive/zip

      - name: Create tagged version
        run: |-

      - name: Create manifest list and pushes
        run: |-
          oras tag  ghcr.io/${{ github.repository_owner }}/opentofu-modules/eks:latest ${{ env.RELEASE_VERSION }}
